version: "3"

services:
  sqlite3:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - ./databases/sqlite3:/root/db/
    ports:
      - "9000:9000" # expose ports - HOST:CONTAINER
    restart: unless-stopped
